// RV: Loading sync scripts is disabled via lint rule; consider dynamic import or `next/script` with proper strategy for performance.
import type { Metadata } from "next";

import "./default-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // RV: Language is hardcoded to "en". Consider sourcing from user config (e.g., `${STADEN_ROOT}/config.yaml` or a context provider).
    <html lang="en">
      <body
        className="
          w-300
          ml-20
          text-primary
          bg-background
        "
      >
        {children}
        <script src="/vega.js" defer />
        <script src="/vega-lite.js" defer />
        <script src="/vega-embed.js" defer />
      </body>
    </html>
  );
}
