import type { Metadata } from "next";
import Script from "next/script";

import "./default-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteLanguage = process.env.NEXT_PUBLIC_SITE_LANGUAGE ?? "en";
  return (
    <html lang={siteLanguage}>
      <body
        className="
          max-w-full
          mx-20
          text-primary
          bg-background
        "
      >
        {children}
        {/* NOTE: we must load these Vega scripts in this order */}
        <Script src="/vega.js" strategy="afterInteractive" />
        <Script src="/vega-lite.js" strategy="afterInteractive" />
        <Script src="/vega-embed.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
